version: '3'
services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app2
